defaults:
  - multi_step_sft_config_a100_2


data:
  split: "train[40%:80%]"


model:
  save_dir: "saved_models/multi_step_ssl/"
  load_from_checkpoint: True


train:
  max_revision_steps: 3 # Number of times an agent is allowed to revise the code, 1 = single turn
  max_gen_length: 256 # Maximum length of generated code
  use_critic: True
  use_ground_truth_responses: False

  # Args for the HuggingFace trainer
  trainer_kwargs:
    output_dir: "train_logs/multi_step_ssl/"
    logging_steps: 5
    max_steps: 1000 # Number of train steps, should be ~3 epochs